/**
 *  Generated by mxmlc 4.0
 *
 *  Package:    components.popup.newFile
 *  Class:      NewJavaFilePopup
 *  Source:     /Users/axgord/dev/Moonshine-IDE/ide/MoonshineSharedCore/src/components/popup/newFile/NewJavaFilePopup.mxml
 *  Template:   flex2/compiler/mxml/gen/ClassDef.vm
 *  Time:       2019.04.22 23:25:49 MSK
 */

package components.popup.newFile;

import actionScripts.events.NewFileEvent;
import actionScripts.extResources.com.validator.ValidatorType;
import actionScripts.utils.SimpleValidator;
import actionScripts.valueObjects.AS3ClassAttributes;
import actionScripts.valueObjects.ConstantsCoreVO;
import mx.events.FlexEvent;

import components.popup.newFile.NewASFilePopup;
import flash.accessibility.*;
import flash.debugger.*;
import flash.display.*;
import flash.errors.*;
import flash.events.*;
import flash.external.*;
import flash.geom.*;
import flash.media.*;
import flash.net.*;
import flash.printing.*;
import flash.profiler.*;
import flash.system.*;
import flash.text.*;
import flash.ui.*;
import flash.utils.*;
import flash.xml.*;
import mx.binding.*;
import mx.core.ClassFactory;
import mx.core.DeferredInstanceFromClass;
import mx.core.DeferredInstanceFromFunction;
import mx.core.IDeferredInstance;
import mx.core.IFactory;
import mx.core.IFlexModuleFactory;
import mx.core.IPropertyChangeNotifier;
import mx.core.Mx_internal;
import mx.filters.*;
import mx.styles.*;

//  begin class def
class NewJavaFilePopup extends components.popup.newFile.NewASFilePopup {

	//  instance variables

	//  type-import dummies

	//  constructor (Flex display object)
	/**
	 * @private
	 **/
	public function new() {
		super();

		// mx_internal::_document = this;

		// layer initializers

		// properties

		// events

	}

	/**
	 * @private
	 **/
	private var __moduleFactoryInitialized:Bool = false;

	/**
	 * @private
	 * Override the module factory so we can defer setting style declarations
	 * until a module factory is set. Without the correct module factory set
	 * the style declaration will end up in the wrong style manager.
	 **/
	override private function set_moduleFactory(factory:IFlexModuleFactory):IFlexModuleFactory {
		super.moduleFactory = factory;

		if (__moduleFactoryInitialized) {
			return factory;
		}

		__moduleFactoryInitialized = true;

		// our style settings

		return factory;
	}

	//  initialize()
	/**
	 * @private
	 **/
	override public function initialize():Void {
		super.initialize();
	}

	//  scripts
	//  <Script>, line 4 - 52

	override private function onBtnCreateClick(event:MouseEvent):Void {
		// validation check for Enter key
		if (!AS3.as(btnCreate.enabled, Bool)) {
			return;
		}

		// validation 2
		var validateArr:Array<Dynamic> = new Array<Dynamic>();
		if (SimpleValidator.validate(validateArr)) {
			var attributes:AS3ClassAttributes = new AS3ClassAttributes();
			attributes.modifierA = 'public';
			attributes.extendsClassInterface = txtSuperclass.text;
			attributes.implementsInterface = txtInterfaces.text;
			attributes.modifierB = '';
			attributes.modifierC = (AS3.as(cbFinal.selected, Bool)) ? 'final' : '';

			attributes.imports = newAsFileCompletionManager.classesImports.concat(newAsFileCompletionManager.interfacesImports);

			var tmpEvent:NewFileEvent = new NewFileEvent(NewFileEvent.EVENT_NEW_FILE, null, ConstantsCoreVO.TEMPLATE_JAVACLASS, wrapperOfFolderLocation, attributes);
			tmpEvent.fileName = txtFileName.text;
			tmpEvent.ofProject = wrapperBelongToProject;
			tmpEvent.fileExtension = this.createdFileExtension;

			dispatchEvent(tmpEvent);

			doBeforeExit();
			super.closeThis();
		}
	}

	override private function onNewFileCreationComplete(event:FlexEvent):Void {
		super.onNewFileCreationComplete(event);

		hasInternalClasses = false;
		cbDynamic.visible = cbDynamic.includeInLayout = false;
		title = (isInterfaceDialog) ? 'New Interface Class' : 'New Java Class';
		createdFileExtension = '.java';
	}

}

//  end package def