/**
 *  Generated by mxmlc 4.0
 *
 *  Package:    actionScripts.plugin.console.setting
 *  Class:      KeySelectSkin
 *  Source:     /Users/axgord/dev/Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/plugin/console/setting/KeySelectSkin.mxml
 *  Template:   flex2/compiler/mxml/gen/ClassDef.vm
 *  Time:       2019.04.22 23:25:49 MSK
 */

package actionScripts.plugin.console.setting;

import flash.accessibility.*;
import flash.debugger.*;
import flash.display.*;
import flash.errors.*;
import flash.events.*;
import flash.external.*;
import flash.geom.*;
import flash.media.*;
import flash.net.*;
import flash.printing.*;
import flash.profiler.*;
import flash.system.*;
import flash.text.*;
import flash.ui.*;
import flash.utils.*;
import flash.xml.*;
import mx.binding.*;
import mx.binding.IBindingClient;
import mx.core.ClassFactory;
import mx.core.DeferredInstanceFromClass;
import mx.core.DeferredInstanceFromFunction;
import mx.core.IDeferredInstance;
import mx.core.IFactory;
import mx.core.IFlexModuleFactory;
import mx.core.IPropertyChangeNotifier;
import mx.core.IStateClient2;
import mx.core.Mx_internal;
import mx.filters.*;
import mx.states.AddItems;
import mx.states.SetProperty;
import mx.states.State;
import mx.styles.*;
import spark.components.Label;
import spark.primitives.BitmapImage;
import spark.skins.SparkSkin;

@:meta(HostComponent(name = 'spark.components.Button'))
@:meta(States(name = 'up', name = 'over', name = 'down', name = 'disabled'))
//  begin class def
class KeySelectSkin extends spark.skins.SparkSkin implements mx.binding.IBindingClient implements mx.core.IStateClient2 {

	//  instance variables
	@:meta(Inspectable())
	/**
	 * @private
	 **/
	public var _KeySelectSkin_BitmapImage1:spark.primitives.BitmapImage;

	@:meta(Inspectable())
	/**
	 * @private
	 **/
	public var _KeySelectSkin_BitmapImage2:spark.primitives.BitmapImage;

	@:meta(Inspectable())
	/**
	 * @private
	 **/
	public var _KeySelectSkin_BitmapImage3:spark.primitives.BitmapImage;

	@:meta(Bindable())
	/**
	 * @private
	 **/
	public var labelElement:spark.components.Label;

	//  type-import dummies

	//  constructor (Flex display object)
	/**
	 * @private
	 **/
	public function new() {
		super();

		// mx_internal::_document = this;

		var bindings:Array<Dynamic> = _KeySelectSkin_bindingsSetup();
		var watchers:Array<Dynamic> = [];

		var target:Dynamic = this;

		if (_watcherSetupUtil == null) {
			var watcherSetupUtilClass:Dynamic = Type.resolveClass('_actionScripts_plugin_console_setting_KeySelectSkinWatcherSetupUtil');
			Reflect.field(watcherSetupUtilClass, 'init')(null);
		}

		_watcherSetupUtil.setup(this,
				function(propertyName:String):Dynamic {
					return Reflect.field(target, propertyName);
				},
				function(propertyName:String):Dynamic {
					return Reflect.getProperty(KeySelectSkin, propertyName);
				},
				bindings,
				watchers
		);

		// mx_internal::_bindings =  //  mx_internal::_bindings.concat(bindings);
		// mx_internal::_watchers =  //  mx_internal::_watchers.concat(watchers);

		// layer initializers

		// properties
		this.mxmlContent = [_KeySelectSkin_Label1_i()];
		this.currentState = 'up';

		// events

		var _KeySelectSkin_BitmapImage1_factory:DeferredInstanceFromFunction =
		new mx.core.DeferredInstanceFromFunction(_KeySelectSkin_BitmapImage1_i);
		var _KeySelectSkin_BitmapImage2_factory:DeferredInstanceFromFunction =
		new mx.core.DeferredInstanceFromFunction(_KeySelectSkin_BitmapImage2_i);
		var _KeySelectSkin_BitmapImage3_factory:DeferredInstanceFromFunction =
		new mx.core.DeferredInstanceFromFunction(_KeySelectSkin_BitmapImage3_i);

		states = [
				new State({
					'name': 'up',
					'overrides': [
					new AddItems().initializeFromObject({
								'itemsFactory': _KeySelectSkin_BitmapImage1_factory,
								'destination': null,
								'propertyName': 'mxmlContent',
								'position': 'first'
							})
			]
				}),
				new State({
					'name': 'over',
					'overrides': [
					new AddItems().initializeFromObject({
								'itemsFactory': _KeySelectSkin_BitmapImage2_factory,
								'destination': null,
								'propertyName': 'mxmlContent',
								'position': 'first'
							})
			]
				}),
				new State({
					'name': 'down',
					'overrides': [
					new AddItems().initializeFromObject({
								'itemsFactory': _KeySelectSkin_BitmapImage3_factory,
								'destination': null,
								'propertyName': 'mxmlContent',
								'position': 'first'
							})
			]
				}),
				new State({
					'name': 'disabled',
					'overrides': [
					new mx.states.SetProperty().initializeFromObject({
								'name': 'alpha',
								'value': 0.5
							})
			]
				})
		];

		for (i in 0...bindings.length) {
			AS3.as(bindings[i], Binding).execute();
		}

	}

	/**
	 * @private
	 **/
	private var __moduleFactoryInitialized:Bool = false;

	/**
	 * @private
	 * Override the module factory so we can defer setting style declarations
	 * until a module factory is set. Without the correct module factory set
	 * the style declaration will end up in the wrong style manager.
	 **/
	override private function set_moduleFactory(factory:IFlexModuleFactory):IFlexModuleFactory {
		super.moduleFactory = factory;

		if (__moduleFactoryInitialized) {
			return factory;
		}

		__moduleFactoryInitialized = true;

		// our style settings

		return factory;
	}

	//  initialize()
	/**
	 * @private
	 **/
	override public function initialize():Void {
		super.initialize();
	}

	//  scripts
	//  <Script>, line 39 - 45

	private static var exclusions(default, never):Array<Dynamic> = cast ['labelElement'];

	override private function get_colorizeExclusions():Array<Dynamic> {
		return exclusions;
	}

	//  end scripts

	//  supporting function definitions for properties, events, styles, effects
	private function _KeySelectSkin_BitmapImage1_i():spark.primitives.BitmapImage {
		var temp:spark.primitives.BitmapImage = new spark.primitives.BitmapImage();
		temp.source = _embed_mxml__elements_gfx_key_btn_up_png_1650924495;
		temp.initialized(this, '_KeySelectSkin_BitmapImage1');
		_KeySelectSkin_BitmapImage1 = temp;
		mx.binding.BindingManager.executeBindings(this, '_KeySelectSkin_BitmapImage1', _KeySelectSkin_BitmapImage1);
		return temp;
	}

	private function _KeySelectSkin_BitmapImage2_i():spark.primitives.BitmapImage {
		var temp:spark.primitives.BitmapImage = new spark.primitives.BitmapImage();
		temp.source = _embed_mxml__elements_gfx_key_btn_over_png_1004329905;
		temp.initialized(this, '_KeySelectSkin_BitmapImage2');
		_KeySelectSkin_BitmapImage2 = temp;
		mx.binding.BindingManager.executeBindings(this, '_KeySelectSkin_BitmapImage2', _KeySelectSkin_BitmapImage2);
		return temp;
	}

	private function _KeySelectSkin_BitmapImage3_i():spark.primitives.BitmapImage {
		var temp:spark.primitives.BitmapImage = new spark.primitives.BitmapImage();
		temp.source = _embed_mxml__elements_gfx_key_btn_down_png_819026729;
		temp.initialized(this, '_KeySelectSkin_BitmapImage3');
		_KeySelectSkin_BitmapImage3 = temp;
		mx.binding.BindingManager.executeBindings(this, '_KeySelectSkin_BitmapImage3', _KeySelectSkin_BitmapImage3);
		return temp;
	}

	private function _KeySelectSkin_Label1_i():spark.components.Label {
		var temp:spark.components.Label = new spark.components.Label();
		temp.percentWidth = 100.0;
		temp.percentHeight = 100.0;
		temp.styleName = 'uiTextSettingsLabel';
		temp.setStyle('textAlign', 'center');
		temp.setStyle('color', 6184542);
		temp.setStyle('verticalAlign', 'middle');
		temp.id = 'labelElement';
		if (!AS3.as(temp.document, Bool)) {
			temp.document = this;
		}
		labelElement = temp;
		mx.binding.BindingManager.executeBindings(this, 'labelElement', labelElement);
		return temp;
	}

	//  binding mgmt
	private function _KeySelectSkin_bindingsSetup():Array<Dynamic> {
		var result:Array<Dynamic> = [];

		result[0] = new mx.binding.Binding(this,
				function():String {
					var result:Dynamic = (hostComponent.label);
					return Std.string((result == null) ? null : Std.string(result));
				},
				null,
				'labelElement.text');

		return result;
	}

	/**
	 * @private
	 **/
	public static var watcherSetupUtil(never, set):IWatcherSetupUtil2;
	private static function set_watcherSetupUtil(watcherSetupUtil:IWatcherSetupUtil2):IWatcherSetupUtil2 {
		(KeySelectSkin)._watcherSetupUtil = watcherSetupUtil;
		return watcherSetupUtil;
	}

	private static var _watcherSetupUtil:IWatcherSetupUtil2;

	//  embed carrier vars
	@:meta(Embed(source = '/elements/gfx/key_btn_over.png'))
	private var _embed_mxml__elements_gfx_key_btn_over_png_1004329905:Class<Dynamic>;

	@:meta(Embed(source = '/elements/gfx/key_btn_up.png'))
	private var _embed_mxml__elements_gfx_key_btn_up_png_1650924495:Class<Dynamic>;

	@:meta(Embed(source = '/elements/gfx/key_btn_down.png'))
	private var _embed_mxml__elements_gfx_key_btn_down_png_819026729:Class<Dynamic>;

	//  end embed carrier vars

	//  binding management vars
	/**
	 * @private
	 **/
	@:ns('mx_internal') private var _bindings:Array<Dynamic> = [];
	/**
	 * @private
	 **/
	@:ns('mx_internal') private var _watchers:Array<Dynamic> = [];
	/**
	 * @private
	 **/
	@:ns('mx_internal') private var _bindingsByDestination:Dynamic = {};
	/**
	 * @private
	 **/
	@:ns('mx_internal') private var _bindingsBeginWithWord:Dynamic = {};

}

//  end package def