/**
 *  Generated by mxmlc 4.0
 *
 *  Package:    actionScripts.plugin.settings.renderers
 *  Class:      ColorRenderer
 *  Source:     /Users/axgord/dev/Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/plugin/settings/renderers/ColorRenderer.mxml
 *  Template:   flex2/compiler/mxml/gen/ClassDef.vm
 *  Time:       2019.04.22 23:25:49 MSK
 */

package actionScripts.plugin.settings.renderers;

import actionScripts.plugin.settings.vo.ColorSetting;
import actionScripts.utils.TextUtil;

import flash.accessibility.*;
import flash.debugger.*;
import flash.display.*;
import flash.errors.*;
import flash.events.*;
import flash.events.MouseEvent;
import flash.external.*;
import flash.geom.*;
import flash.media.*;
import flash.net.*;
import flash.printing.*;
import flash.profiler.*;
import flash.system.*;
import flash.text.*;
import flash.ui.*;
import flash.utils.*;
import flash.xml.*;
import mx.binding.*;
import mx.binding.IBindingClient;
import mx.controls.Spacer;
import mx.core.ClassFactory;
import mx.core.DeferredInstanceFromClass;
import mx.core.DeferredInstanceFromFunction;
import mx.core.IDeferredInstance;
import mx.core.IFactory;
import mx.core.IFlexModuleFactory;
import mx.core.IPropertyChangeNotifier;
import mx.core.Mx_internal;
import mx.events.FlexEvent;
import mx.filters.*;
import mx.styles.*;
import spark.components.HGroup;
import spark.components.Label;
import spark.components.TextInput;
import spark.events.TextOperationEvent;

//  begin class def
class ColorRenderer extends spark.components.HGroup implements mx.binding.IBindingClient {

	//  instance variables
	/**
	 * @private
	 **/
	public var _ColorRenderer_Label1:spark.components.Label;

	@:meta(Bindable())
	/**
	 * @private
	 **/
	public var text:spark.components.TextInput;

	//  type-import dummies

	//  constructor (Flex display object)
	/**
	 * @private
	 **/
	public function new() {
		super();

		// mx_internal::_document = this;

		var bindings:Array<Dynamic> = _ColorRenderer_bindingsSetup();
		var watchers:Array<Dynamic> = [];

		var target:Dynamic = this;

		if (_watcherSetupUtil == null) {
			var watcherSetupUtilClass:Dynamic = Type.resolveClass('_actionScripts_plugin_settings_renderers_ColorRendererWatcherSetupUtil');
			Reflect.field(watcherSetupUtilClass, 'init')(null);
		}

		_watcherSetupUtil.setup(this,
				function(propertyName:String):Dynamic {
					return Reflect.field(target, propertyName);
				},
				function(propertyName:String):Dynamic {
					return Reflect.getProperty(ColorRenderer, propertyName);
				},
				bindings,
				watchers
		);

		// mx_internal::_bindings =  //  mx_internal::_bindings.concat(bindings);
		// mx_internal::_watchers =  //  mx_internal::_watchers.concat(watchers);

		// layer initializers

		// properties
		this.percentWidth = 100.0;
		this.paddingLeft = 15;
		this.paddingRight = 15;
		this.mxmlContent = [_ColorRenderer_Label1_i(), _ColorRenderer_Spacer1_c(), _ColorRenderer_TextInput1_i()];

		// events
		this.addEventListener('creationComplete', ___ColorRenderer_HGroup1_creationComplete);

		for (i in 0...bindings.length) {
			AS3.as(bindings[i], Binding).execute();
		}

	}

	/**
	 * @private
	 **/
	private var __moduleFactoryInitialized:Bool = false;

	/**
	 * @private
	 * Override the module factory so we can defer setting style declarations
	 * until a module factory is set. Without the correct module factory set
	 * the style declaration will end up in the wrong style manager.
	 **/
	override private function set_moduleFactory(factory:IFlexModuleFactory):IFlexModuleFactory {
		super.moduleFactory = factory;

		if (__moduleFactoryInitialized) {
			return factory;
		}

		__moduleFactoryInitialized = true;

		// our style settings

		return factory;
	}

	//  initialize()
	/**
	 * @private
	 **/
	override public function initialize():Void {
		super.initialize();
	}

	//  scripts
	//  <Script>, line 33 - 73

	@:meta(Bindable())
	public var setting:ColorSetting;

	private function commitValue():Void {
		if (text.text.indexOf('#') == 0) {
			setting.value = as3hx.Compat.parseInt('0x' + text.text.substr(1), 16);
			return;
		}
		if (text.text.indexOf('0x') == 0) {
			setting.value = as3hx.Compat.parseInt(text.text, 16);
			return;
		}

		if (!AS3.as(Math.isNaN(as3hx.Compat.parseInt(text.text)), Bool)) {
			setting.value = as3hx.Compat.parseInt(text.text);
		} else {
			setting.value = 0;
		}
	}

	private function getColor():String {
		return '#' + TextUtil.padLeft(Std.string(as3hx.Compat.toString(setting.value, 16).toUpperCase()), 6);
	}

	private function focusIn():Void {
		text.setFocus();
	}

	//  end scripts

	//  supporting function definitions for properties, events, styles, effects
	private function _ColorRenderer_Label1_i():spark.components.Label {
		var temp:spark.components.Label = new spark.components.Label();
		temp.styleName = 'uiTextSettingsLabel';
		temp.setStyle('paddingTop', 15);
		temp.setStyle('paddingBottom', 15);
		temp.addEventListener('mouseDown', ___ColorRenderer_Label1_mouseDown);
		temp.id = '_ColorRenderer_Label1';
		if (!AS3.as(temp.document, Bool)) {
			temp.document = this;
		}
		_ColorRenderer_Label1 = temp;
		mx.binding.BindingManager.executeBindings(this, '_ColorRenderer_Label1', _ColorRenderer_Label1);
		return temp;
	}

	/**
	 * @private
	 **/
	public function ___ColorRenderer_Label1_mouseDown(event:flash.events.MouseEvent):Void {
		focusIn();
	}

	private function _ColorRenderer_Spacer1_c():mx.controls.Spacer {
		var temp:mx.controls.Spacer = new mx.controls.Spacer();
		temp.percentWidth = 100.0;
		if (!AS3.as(temp.document, Bool)) {
			temp.document = this;
		}
		return temp;
	}

	private function _ColorRenderer_TextInput1_i():spark.components.TextInput {
		var temp:spark.components.TextInput = new spark.components.TextInput();
		temp.styleName = 'uiTextSettingsValue';
		temp.percentHeight = 100.0;
		temp.minWidth = 250;
		temp.restrict = '0-9a-fA-Fx#';
		temp.setStyle('textAlign', 'right');
		temp.setStyle('borderVisible', false);
		temp.setStyle('contentBackgroundAlpha', 0);
		temp.setStyle('focusAlpha', 0);
		temp.addEventListener('change', __text_change);
		temp.id = 'text';
		if (!AS3.as(temp.document, Bool)) {
			temp.document = this;
		}
		text = temp;
		mx.binding.BindingManager.executeBindings(this, 'text', text);
		return temp;
	}

	/**
	 * @private
	 **/
	public function __text_change(event:spark.events.TextOperationEvent):Void {
		commitValue();
	}

	/**
	 * @private
	 **/
	public function ___ColorRenderer_HGroup1_creationComplete(event:mx.events.FlexEvent):Void {
		text.text = getColor();
	}

	//  binding mgmt
	private function _ColorRenderer_bindingsSetup():Array<Dynamic> {
		var result:Array<Dynamic> = [];

		result[0] = new mx.binding.Binding(this,
				function():String {
					var result:Dynamic = (setting.label);
					return Std.string((result == null) ? null : Std.string(result));
				},
				null,
				'_ColorRenderer_Label1.text');

		return result;
	}

	/**
	 * @private
	 **/
	public static var watcherSetupUtil(never, set):IWatcherSetupUtil2;
	private static function set_watcherSetupUtil(watcherSetupUtil:IWatcherSetupUtil2):IWatcherSetupUtil2 {
		(ColorRenderer)._watcherSetupUtil = watcherSetupUtil;
		return watcherSetupUtil;
	}

	private static var _watcherSetupUtil:IWatcherSetupUtil2;

	//  embed carrier vars
	//  end embed carrier vars

	//  binding management vars
	/**
	 * @private
	 **/
	@:ns('mx_internal') private var _bindings:Array<Dynamic> = [];
	/**
	 * @private
	 **/
	@:ns('mx_internal') private var _watchers:Array<Dynamic> = [];
	/**
	 * @private
	 **/
	@:ns('mx_internal') private var _bindingsByDestination:Dynamic = {};
	/**
	 * @private
	 **/
	@:ns('mx_internal') private var _bindingsBeginWithWord:Dynamic = {};

}

//  end package def